#!/usr/bin/python3

import time
import requests
import os
import sys


import RPi.GPIO as GPIO

#Disable warnings (optional)
GPIO.setwarnings(False)
#Select GPIO mode
GPIO.setmode(GPIO.BCM)
#Set buzzer - pin 23 as output
buzzer=23 
GPIO.setup(buzzer, GPIO.OUT)

HOSTNAME = sys.argv[1]


def check_server_status():
    response = os.system("ping -c 1 -w2 " + HOSTNAME + " > /dev/null 2>&1")
    resp = requests.get("http://{}/nextcloud/status.php".format(HOSTNAME))
    print("Ping response recieved: {} and HTTP Status Code: {}".format(response, resp.status_code))
    if resp.status_code != 200:
        print("HOST: {} is offline".format(HOSTNAME))
        GPIO.output(buzzer, GPIO.HIGH)
        time.sleep(0.5) # Delay in seconds
        GPIO.output(buzzer, GPIO.LOW)
        time.sleep(0.5)

def main():
    appName = os.path.basename(sys.argv[0]).split('-')[-1]
    print(appName)
    check_server_status()

if __name__ == "__main__":
    main()
